### ISSUE TITLE
Let addKey return the id of the inserted key

### ISSUE THREAD

**Issue by benj-zen** [zervnet/pdns#4]
This has to be done for all backends:

High Priority:
- [x] Generic MySQL _tested_
- [x] Generic ODBC _tested_
- [x] Generic PostgreSQL _tested_
- [x] Generic SQLite3 _tested_
- [x] BIND _tested_

Lower Priority:
- [ ] Generic Oracle
- [ ] GeoIP
- [ ] LDAP
- [ ] MyDNS
- [ ] OpenDBX
- [ ] Oracle
- [ ] Pipe
- [ ] Random
- [ ] Remote
- [ ] TinyDNS

**Comment by MrM0nkey** [comment]
I'll take care of ODBC.

**Comment by taudor** [comment]
I'll take PostgreSQL

**Comment by zervnet** [comment]
ich hab gestern abend mit BIND angefangen
